# Generated by Django 3.0.4 on 2020-04-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('range', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='deprture_airport',
            new_name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='id',
        ),
        migrations.RemoveField(
            model_name='airports',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='airports',
            name='airport_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airports',
            name='airport_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airports',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airports',
            name='coordinates',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=3)),
                ('fare_conditions', models.CharField(max_length=250)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.PositiveIntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_id1', to='airtrans.TicketFlight')),
                ('seat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Seat')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_no1', to='airtrans.TicketFlight')),
            ],
            options={
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
    ]
